version: '3.8'

services:
  db:
    container_name: postgres
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: go-mailing
    ports:
      - "5432:5432"

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - "3333:8080"
    environment:
      ADMINER_DESIGN: dracula
